### ISSUE TITLE
Coderisk.com rates the plugin with 82 (red)

### ISSUE THREAD

**Issue by robertoschwald** [rhubarbgroup/email-address-encoder#12]
Any known flaws in the plugin you are aware of?

https://coderisk.com/wp/plugin/email-address-encoder

**Comment by tillkruss** [comment]
No, it's only 849 lines of code, so super easy to review.

They don't provide ANY value whatsoever, no hints to what's "wrong".

They force me to sign up, then when trying to verify ownership they want me to link back to their site "for verification", but don't explain what "hidden link in the description of your plugin" actually means.

**Comment by robertoschwald** [comment]
Its "Currently our system looks for the hidden link with the random token in the Wordpress plugin description"

**Comment by robertoschwald** [comment]
e.g. see source of https://wordpress.org/plugins/favicon-by-realfavicongenerator/

**Comment by tillkruss** [comment]
I don't understand. Please post a direct link to the file.

**Comment by robertoschwald** [comment]
In the description of the plugin, you need to place the hidden link from coderisk, so they can proove you are the owner of the plugin.
In the example URL I posted above, it is:

    `<p><a href="http://coderisk.com/wp/plugin/favicon-by-realfavicongenerator/RIPS-TVYsdQTMAr" rel="nofollow ugc"></a></p>`

**Comment by tillkruss** [comment]
Thanks.

Both are false positive issues.

**Comment by tillkruss** [comment]
<img width="1131" alt="Screen Shot 2020-05-28 at 10 10 09 AM" src="https://user-images.githubusercontent.com/665029/83171759-6dd98a80-a0cb-11ea-9633-b182330d2b20.png">

**Comment by tillkruss** [comment]
I just released 1.0.21, I'll wait for the next scan to occur.

**Comment by robertoschwald** [comment]
Top! 

You may run static analysis yourself using Exakat. I use it with Docker here, e.g.:
```
docker pull exakat/exakat

docker run -it -v $(pwd)/projects:/usr/src/exakat/projects --rm --name my-exakat exakat/exakat exakat init -p email-encoder -R https://github.com/tillkruss/email-encoder.git

docker run -it -v $(pwd)/projects:/usr/src/exakat/projects --rm --name my-exakat exakat/exakat exakat project -p email-encoder

open projects/email-encoder/report/index.html
```

**Comment by tillkruss** [comment]
New version still flagged with the same two issues. I'm going to close this and ignore the score. No value in this particular use case.
