### ISSUE TITLE
Why is this plugin encoding my lazy loaded images?

### ISSUE THREAD

**Issue by gotjoshua** [rhubarbgroup/email-address-encoder#13]
I recently installed this plugin and was happy to see that the mailto: addresses were automatically encoded/protected! Thanks for the easy install.

Unfortunately I also discovered that it was encoding the src-set urls for my lazy load images!!! This is really bad, because when I produce a static version of the site, the obfuscated/encoded urls are not found and the production site ends up pointing at the dev site!

Is there (or could there be) a setting to disable this behavior?

I want the plugin to ONLY affect mailto: urls

many thanks!

Cross posted:
https://wordpress.org/support/topic/why-is-this-plugin-encoding-my-lazy-loaded-images/

**Comment by tillkruss** [comment]
Hi @gotjoshua, I've seen this before and unfortunately there isn't anything I can do about the RegEx picking up the image URLs. The [Premium version](https://encoder.till.im/download) however handles them without issues, because of its different architecture.

**Comment by gotjoshua** [comment]
Hello @tillkruss, thanks for your reply...
This is not a very trust inspiring answer. I understand that you want people to pay for the premium version, and it is of course very generous that you offer a free version of your plugin... AND RegEx can do anything.

You are offering a plugin called email-encoder...  not encode-anything-that-includes-an-@-sign ...

**Comment by tillkruss** [comment]
You can use your own regex, or even exclude matches from the current regex, if the plugins defaults aren't good enough for you. 

https://encoder.till.im/guide

**Comment by gotjoshua** [comment]
Hi again, Thanks for the pointer to the guide @tillkruss 
I am trying to use the [encode link""] syntax to encode an email and it seems to fully ignore all attributes from the short code:
https://github.com/tillkruss/email-encoder/blob/master/email-address-encoder.php#L97

Is this supposed to work in the free version?

**Comment by tillkruss** [comment]
@gotjoshua: The free version only supports: `[encode]text to encode[/encode]`, the Premium version supports the `technique` and `link` attributes. However you're welcome to submit a PR and add this functionality.

**Comment by gotjoshua** [comment]
done. #14 

cheers...

**Comment by gotjoshua** [comment]
Just for documentation, if anyone finds this issue:

Image URLS that include an @ sign will be found by this plugin and encoded "unintentionally"
eg. images that include @2x ( [Retina Naming Convention](https://www.lynda.com/Photoshop-tutorials/Understanding-retina-naming-conventions/133344/379094-4.html) )

So to avoid this I decided to do the following:
1. Install and enable the plugin
2. choose "Nothing, don't do anything" in the settings
3. Use the [encode] short-code to manually encode emails like this:
```
[encode link="mailto:your@email.org"]your@email.org[/encode]
```
note: this requires the plug-in to be updated after @tillkruss merges #14
