### ISSUE TITLE
Encode Email and add as parameter a CSS-Class ...

### ISSUE THREAD

**Issue by ghost** [rhubarbgroup/email-address-encoder#15]
Hello dear PHP-Developer, it would be nice if you could add the posibility to add a CSS-CLASS to the email encoder like:
[encode link="mailto:steve@apple.com" class="MY-OWN-CSS-CLASS"]Email: steve@apple.com[/encode]
Thank you and best regards from Germany

**Comment by tillkruss** [comment]
Yeah, do you want to open a PR with support for it?
