### ISSUE TITLE
Some PHP Notices and Warning in Debug mode

### ISSUE THREAD

**Issue by SupaMic** [rhubarbgroup/email-address-encoder#16]
Notice: Undefined property: stdClass::$plugin in /home/public_html/staging/wp-includes/class-wp-list-util.php on line 167
Notice: Undefined property: stdClass::$plugin in /home/public_html/staging/wp-includes/class-wp-list-util.php on line 167
Warning: Cannot modify header information - headers already sent by (output started at /home/public_html/staging/wp-includes/class-wp-list-util.php:167) in /home/public_html/staging/wp-admin/admin-header.php on line 9

I was debugging some separate issues for a client and found that when I turned your deactivated the free version of your plugin these notices and warnings disappeared.  Since it is WP core giving the errors I'm not sure I can help on the cause but I thought I'd pass along.

I can reliably recreate by going to the Add New Plugin page as an Admin on the backend.

Great plugin by the way!  I have tested several other WP plugins with a "professional/clandestine" email scraper and your was the only one that truly worked.

**Comment by tillkruss** [comment]
I can't replicate this, can you post the full stack trace?

**Comment by SupaMic** [comment]
Upon further review, I possibly gave some incorrect data that may have impacted this issue.  I had the pro version (not free) without the license entered because it was on the staging subdomain.  On the production site with the license entered I cannot replicate the issue so most likely something to do with that or a conflict with another plugin on our staging, in either case I'd say you can resolve this issue.

Thanks
