### ISSUE TITLE
Email Address Encoder conflicts

### ISSUE THREAD

**Issue by mickaelmaury** [rhubarbgroup/email-address-encoder#17]
On the site [](https://edvc.fr/ )we have just activated the **Email Address Encoder** extension in its latest version.

This one causes conflicts that I had never encountered before:

- with the search for WordPress extensions from the menu **Extensions > Add**: no search succeeds (loading does not end)

- with **EWWW** extension from **Media > Mass Optimization**: error "Received an invalid response from your website, please check your browser's developer tools console for errors."

// TypeError: window.wp.deprecateL10nObject is not a function. (In 'window.wp.deprecateL10nObject("communityEventsData.l10n",window.communityEventsData.l10n,"5.6.0")', 'window.wp.deprecateL10nObject' is undefined) in dashboard.min.js

- with the **Easy Updates Manager** extension: all data entered in **Dashboard > Updates options** stops loading (values ​​of input fields)

Disabling the **Email Address Encoder** extension solves the problems, the same if I check the "**Register the output buffer early**" option for "**Buffer priority**" in the configuration of the **Email Address Encoder** extension.

Here is some information about my technical environment:

`
### wp-core ###

version: 6.0.1
site_language: fr_FR
user_language: fr_FR
timezone: Europe/Paris
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 5
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/oinspirafb/edvc
wordpress_size: loading...
uploads_path: /home/oinspirafb/edvc/wp-content/uploads
uploads_size: loading...
themes_path: /home/oinspirafb/edvc/wp-content/themes
themes_size: loading...
plugins_path: /home/oinspirafb/edvc/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: Pustaka Child (pustaka-child)
version: 1.0
author: Your Name
author_website: http://tokomoo.com
parent_theme: Pustaka (pustaka)
theme_features: core-block-patterns, post-thumbnails, post-formats, html5, tokoo-testimonials, tokoo-slider, custom-logo, widgets-block-editor, title-tag, automatic-feed-links, custom-header, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, woocommerce, widgets, menus
theme_path: /home/oinspirafb/edvc/wp-content/themes/pustaka-child
auto_update: Désactivé

### wp-parent-theme ###

name: Pustaka (pustaka)
version: 2.11.6
author: Tokomoo
author_website: http://tokomoo.com
theme_path: /home/oinspirafb/edvc/wp-content/themes/pustaka
auto_update: Désactivé

### wp-themes-inactive (1) ###

Twenty Twenty-Two: version: 1.2, author: L’équipe WordPress, Mises à jour auto désactivées

### wp-mu-plugins (1) ###

ManageWP - Worker Loader: author: GoDaddy, version: (undefined)

### wp-plugins-active (32) ###

Akismet Anti-Spam: version: 4.2.5, author: Automattic, Mises à jour auto désactivées
All In One WP Security: version: 4.4.12, author: All In One WP Security & Firewall Team, Mises à jour auto désactivées
Broken Link Checker: version: 1.11.17, author: WPMU DEV, Mises à jour auto désactivées
Classic Editor: version: 1.6.2, author: WordPress Contributors, Mises à jour auto désactivées
Contact Form 7: version: 5.6.1, author: Takayuki Miyoshi, Mises à jour auto désactivées
Custom Favicon: version: 1.0.3, author: Harish Chouhan, Mises à jour auto désactivées
Easy FancyBox: version: 1.8.18, author: RavanH, Mises à jour auto désactivées
Easy Updates Manager: version: 9.0.13, author: Easy Updates Manager Team, Mises à jour auto désactivées
Email Address Encoder ✪: version: 0.3.10, author: Till Krüss, Mises à jour auto désactivées
Enable jQuery Migrate Helper: version: 1.3.0, author: The WordPress Team, Mises à jour auto désactivées
EWWW Image Optimizer: version: 6.7.0, author: Exactly WWW, Mises à jour auto désactivées
Flexible Shipping: version: 4.13.2, author: Octolize, Mises à jour auto désactivées
KingComposer: version: 2.9.5, author: King-Theme, Mises à jour auto désactivées
Loco Translate: version: 2.6.2, author: Tim Whitlock, Mises à jour auto désactivées
Mailchimp for WooCommerce: version: 2.7.1, author: Mailchimp, Mises à jour auto désactivées
ManageWP - Worker: version: 4.9.14, author: GoDaddy, Mises à jour auto désactivées
Minimal Coming Soon & Maintenance Mode: version: 2.35, author: WebFactory Ltd, Mises à jour auto désactivées
Packlink PRO Shipping: version: 3.2.10, author: Packlink Shipping S.L., Mises à jour auto désactivées
PayPlug pour WooCommerce (Officiel): version: 1.8.2, author: PayPlug, Mises à jour auto désactivées
Pustaka Addons: version: 0.1.1, author: tokomoo, Mises à jour auto désactivées
Really Simple SSL: version: 5.3.2, author: Really Simple Plugins, Mises à jour auto désactivées
Site Kit by Google: version: 1.79.1, author: Google, Mises à jour auto désactivées
Tokoo Vitamins: version: 6.5.1, author: alispx, Mises à jour auto désactivées
UpdraftPlus - Backup/Restore: version: 1.22.14, author: UpdraftPlus.Com, DavidAnderson, Mises à jour auto désactivées
WooCommerce: version: 6.7.0, author: Automattic, Mises à jour auto désactivées
WooCommerce Book Store by 99plugins: version: 1.3.2, author: 99plugins, Mises à jour auto désactivées
WooCommerce Customer/Order CSV Export: version: 4.3.7, author: SkyVerge, Mises à jour auto désactivées
WooCommerce PDF Invoices & Packing Slips: version: 3.0.0, author: WP Overnight, Mises à jour auto désactivées
WPFront Notification Bar: version: 3.2.0, author: Syam Mohan, Mises à jour auto désactivées
WP Rocket: version: 3.11.4.2, author: WP Media, Mises à jour auto désactivées
Yoast Duplicate Post: version: 4.5, author: Enrico Battocchi & Team Yoast, Mises à jour auto désactivées
Yoast SEO: version: 19.4, author: Team Yoast, Mises à jour auto désactivées

### wp-media ###

image_editor: EWWWIO_Imagick_Editor
imagick_module_version: 1673
imagemagick_version: ImageMagick 6.8.9-9 Q16 i586 2019-12-29 http://www.imagemagick.org
imagick_version: 3.5.1
file_uploads: File uploads is turned off
post_max_size: 130M
upload_max_filesize: 128M
max_effective_size: 128 Mo
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.26

### wp-server ###

server_architecture: Linux 4.14.253-ovh-vps-grsec-zfs-classid x86_64
httpd_software: Apache
php_version: 7.3.32
php_sapi: fpm-fcgi
max_input_variables: 16000
time_limit: 165
memory_limit: 512M
max_input_time: -1
upload_max_filesize: 128M
php_post_max_size: 130M
curl_version: 7.38.0 OpenSSL/1.0.1t
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.6.51-log
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $
max_allowed_packet: 33554432
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: https://edvc.fr
WP_CONTENT_DIR: /home/oinspirafb/edvc/wp-content
WP_PLUGIN_DIR: /home/oinspirafb/edvc/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: false
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Indéfini
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### google-site-kit ###

version: 1.79.1
php_version: 7.3.32
wp_version: 6.0.1
reference_url: https://edvc.fr
amp_mode: no
site_status: connected-site
user_status: authenticated
verification_status: verified-non-site-kit
connected_user_count: 2
active_modules: site-verification, search-console, analytics, analytics-4, pagespeed-insights
recoverable_modules: none
required_scopes: 
	openid: ✅
	https://www.googleapis.com/auth/userinfo.profile: ✅
	https://www.googleapis.com/auth/userinfo.email: ✅
	https://www.googleapis.com/auth/siteverification: ✅
	https://www.googleapis.com/auth/webmasters: ✅
	https://www.googleapis.com/auth/analytics.readonly: ✅
capabilities: 
	googlesitekit_authenticate: ✅
	googlesitekit_setup: ✅
	googlesitekit_view_posts_insights: ✅
	googlesitekit_view_dashboard: ✅
	googlesitekit_manage_options: ✅
	googlesitekit_view_splash: ✅
	googlesitekit_view_authenticated_dashboard: ✅
	googlesitekit_view_wp_dashboard_widget: ✅
	googlesitekit_view_admin_bar_menu: ✅
enabled_features: 
	adsenseSetupV2: ✅
	dashboardSharing: ⭕
	ga4ActivationBanner: ⭕
	ideaHubModule: ⭕
	twgModule: ⭕
	userInput: ⭕
	zeroDataStates: ✅
search_console_property: https://edvc.fr/
analytics_account_id: 7926••••
analytics_property_id: UA-7926•••••••
analytics_profile_id: 2203•••••
analytics_use_snippet: yes
analytics_4_property_id: 3246942••
analytics_4_web_data_stream_id: 3860••••••
analytics_4_measurement_id: G-2C••••••••
analytics_4_use_snippet: yes

`

**Comment by tillkruss** [comment]
If `Register the output buffer early` works great 👍

I'm open to pull requests if you got a solution.
