### ISSUE TITLE
Moving License for Professional Plan

### ISSUE THREAD

**Issue by bfinke4** [rhubarbgroup/email-address-encoder#7]
Hi I recently purchased the professional plan.  I set it up on my dev server to work though it.  But now that I want to move the license to my live site it is telling me that the license key is already registered.  Which I get.  How can I move it?  I deleted the license key on the dev, but that didn't seem to work.  Thank you for you help

Brian

**Comment by tillkruss** [comment]
Hey Brian! The domain gets disabled when the plugin is uninstalled, but I'll be sure to also do that when the license key is removed. Maybe add a little link to the field as well.

Email me at `encoder [at] till [dot] im` and I'll help you out.
