### ISSUE TITLE
JavaScript causing each page to be loaded twice

### ISSUE THREAD

**Issue by bobbingwide** [rhubarbgroup/email-address-encoder#8]
Hi, I' was looking at server logs and noticed that every request was being performed twice. Once by the user and then again by the JavaScript.
`/wp-content/plugins/email-address-encoder/includes/email-detector.js?ver=1.0.19`

The screen capture shows the request being sent to `s.b/ebps` - which is a directory install in my local development environment.  It's happening on the live system too. 

 I don't understand why this code is necessary. It's doubling the server workload.

![image](https://user-images.githubusercontent.com/2474435/56302912-af5ede80-6132-11e9-9e2b-14f1e1078089.png)

**Comment by tillkruss** [comment]
Here are the conditions when this script is loaded: https://github.com/tillkruss/email-encoder/blob/79f1cec8e4c279378f48633e6e38693c7be8bf57/includes/admin.php#L174-L212

If you have dozens of users with the `manage_options` capability, then you might want to check the "Hide notices and promotions for all users" option.

It's necessary to load the raw HTML, which JavaScript doesn't have access to, so it can't be performed on the same request.

**Comment by bobbingwide** [comment]
> It's necessary to load the raw HTML, which JavaScript doesn't have access to, so it can't be performed on the same request.

Hi, it's a long time since I raised this. I never understood your reply. 
Can you explain why the JavaScript doesnt have access to the HTML on the page that's already been loaded? Why do you need to fetch the whole page again?

**Comment by tillkruss** [comment]
The separate call is to fetch the page as an anonymous guest, without the current’s user email address being in the admin bar, contact forms, or similar. 

Additionally, the script only loads when a user is logged in and is and administrator. Regular users won’t get the script.

**Comment by bobbingwide** [comment]
> Additionally, the script only loads when a user is logged in and is and administrator.

And can I ask the purpose of this? If the user's logged in and an administrator then why do email addresses need to be obfuscated?

**Comment by tillkruss** [comment]
The script doesn’t obfuscate, it adds a warning to the admin bar if unprotected email addresses are found.

**Comment by bobbingwide** [comment]
Thanks for that. I now understand what it's doing. I created an example where an email address was part of the author profile and saw the message in the admin bar. 

I still don't understand why you need to fetch the page again.

**Comment by tillkruss** [comment]
I’d suggest re-reading the thread or play with the code.

**Comment by bobbingwide** [comment]
> It's necessary to load the raw HTML, which JavaScript doesn't have access to, so it can't be performed on the same request.

Are you saying that the JavaScript can't tell which email addresses had been protected since they've already been converted to what the user sees?

**Comment by tillkruss** [comment]
> It's necessary to load the raw HTML, which JavaScript doesn't have access to, so it can't be performed on the same request.

**Comment by bobbingwide** [comment]
Did you mean to add Yes to your reply? 

Whatever the answer, we have opted to tick the checkbox.
