### ISSUE TITLE
Chrome Opens a blank page

### ISSUE THREAD

**Issue by nseeger** [rhubarbgroup/email-address-encoder#9]
Hi,

I spent a lot of time chasing this down but looks to only happen with the plugin turned on. With a mailto link on Chrome, when you click on the link, it will open a blank page with "mailto:theiremail@email.com" text in the upper left corner. 

The email default program does open for people, but it confused the heck out of one of my clients. Doesn't appear to happen on FireFox or Safari. I'm on a Mac but asked PC people to also try it out. Seems specific to Chrome universally, blank page opened for all of us.

In the settings I have ROT13 encoding set and full page scanning.
![Screen Shot 2019-09-05 at 6 18 25 PM](https://user-images.githubusercontent.com/1195587/64387368-c2068100-d009-11e9-88d8-e6c87aaf2ab3.png)

**Comment by tillkruss** [comment]
Can you post (or email) me a link to the specific page that you're having issues with?

**Comment by nseeger** [comment]
Here is an older site example:
https://waranch-brown.com/attorneys/michelle-l-dian/

**Comment by tillkruss** [comment]
Thanks! Could you try the ROT47 technique and see if that works better?

**Comment by nseeger** [comment]
Just tried it on two websites, that does seem to work better now. We had someone let us know they had an issue with the ROT47 method but didn't let me know what exactly happened. So we tried lowering it and noticed the blank window issue in Chrome. 

Problem with the higher level, if someone whose system isn't set properly to auto select their email program of choice or is on a guest computer, they can't copy and past the email address with ROT47. Probably a good thing for spambots, but I'm not sure how to please the technically challenged. Which level would you recommend?

**Comment by tillkruss** [comment]
I just tested your page and ROT47 seems to work in Chrome. Maybe Chrome changed something recently. I'll look into it.

However, ROT47 is way safer anyhow 👍🏻

**Comment by nseeger** [comment]
Yes safer. I may be missing the point, a copy and paste will not work with the ROT47 scenario. For someone not on their computer, they may need to copy the email address. Do all of them scramble the email address? We got a huge complaint on that so my goal is to not only be safe but allow people who may not be on their computer who can't use a mailto link and are trying to just copy it.

**Comment by tillkruss** [comment]
I found a solution for the Chrome issue and it will go live with 0.3.4.

I also see the issue with emails not being selectable. I'll see if I can find a better solution for the ROT47 technique.
